--FIRST TABLE
CREATE TABLE IF NOT EXISTS Youtubers_of_India(
      SNO TEXT PRIMARY KEY,
      NAME TEXT,
      WORK TEXT,
      CHANNEL_NAME TEXT,
      SUBSCRIBERS INTEGER
);  
INSERT INTO Youtubers_of_India (SNO, NAME, WORK, CHANNEL_NAME, SUBSCRIBERS)
VALUES
      ('1', 'UJJWAL CHAURASIYA', 'GAMING AND VLOGGING', 'TECHNO GAMERZ', 30000000),
      ('2', 'NITESH', 'GAMING', 'GAMING ENGINEER', 991000),
      ('3', 'NISCHAY MALHAAN', 'VLOGGING AND GAMING', 'GAMING INSAAN', 20000000),
      ('4', 'JIMMY DONALDSON', 'GAMING AND VLOGGING', 'MR. BEAST', 500000000),
      ('5', 'SOURAV JOSHI', 'VLOGGING', 'SOURAV JOSHI VLOGS', 60000000);

SELECT * FROM Youtubers_of_India;

-- SECOND TABLE
CREATE TABLE IF NOT EXISTS BEAUTIFUL_PLACES_of_INDIA(
      SNO TEXT PRIMARY KEY,
      NAME TEXT,
      STATE_NAME TEXT,
      WHEN_IT_WAS_BUILT INTEGER
);
INSERT INTO BEAUTIFUL_PLACES_of_INDIA (SNO, NAME, STATE_NAME, WHEN_IT_WAS_BUILT)
VALUES
      ('1', 'TAJ MAHAL', 'UTTAR PRADESH', 1632),
      ('2', 'HAWA MAHAL', 'RAJASTHAN', 1799), 
      ('3', 'INDIA GATE', 'NEW DELHI', 1921),
      ('4', 'GATEWAY OF INDIA', 'MAHARASHTRA', 1911), 
      ('5', 'QUTB MINAR', 'NEW DELHI', 1119);

SELECT * FROM BEAUTIFUL_PLACES_of_INDIA;